[toolchain]
channel = "stable"
# https://rust-lang.github.io/rustup/concepts/components.html
components = [ "rust-src" ]
targets = [ "wasm32-unknown-unknown", "aarch64-unknown-linux-gnu", "x86_64-unknown-linux-gnu" ]
profile = "default"